### ISSUE TITLE
Can't import project which worked fine with Idea 2016.2

### ISSUE THREAD

**Issue by lustefaniak** [JetBrains/sbt-structure#46]
When I try to refresh project I get:
```
<set>:1: error: value lang is not a member of sbt.TaskKey[java.io.File]
SettingKey[java.lang.String]("sbt-structure-options") in Global := "download, resolveClassifiers, resolveSbtClassifiers"
```

**Comment by lustefaniak** [comment]
Ok, looks like it will be fixed: https://github.com/JetBrains/sbt-structure/issues/38
